### ISSUE TITLE
How to get a Tile's x, y coordinates in 0.7.0?

### ISSUE THREAD

**Issue by supagu** [flame-engine/tiled.dart#27]
0.6.0 had an x and y value for the Tile, in 0.7.0 this is missing, so if I pass a tile around I can't generate its world coordinates unless you know its row/column values.

Also it would seem helpful for a Tile to have a reference back to the TileLayer it belongs too.

**Comment by luanpotter** [comment]
Do you mean the `computeDrawRect` method? I think that was just moved to the tileset.

```dart
tileSet.computeDrawRect(tile)
```

That's because it requires a few info from the tileset, there was no way to do it only with a `Tile`.

That being said, I don't see why not have a reference to the tileset inside each tile, so that you can easily grab that data.

If that doesn't cause any issues, I think we can definitely do it!
